<?php declare( strict_types = 1 );
namespace CodeKandis\CheckList\Frontend\Templates\Plain;

$htmlTitle = 'Signin';
require_once __DIR__ . '/Common/htmlHeader.phtml';
?>
	<body>
	<div id="page">
		<header class="container-fluid">
		</header>
		<section class="content container-fluid">
			<h1 class="row">
				<span class="col"><?php echo $htmlTitle; ?></span>
			</h1>
			<form action="./" method="POST" enctype="multipart/form-data" class="row">
				<div class="col">
					<div class="row mb-3">
						<div class="col-xxl-3 col-xl-4 col-lg-5 col-md-6 col-sm-12">
							<input type="text" name="name" required placeholder="E-Mail" class="form-control"/>
						</div>
					</div>
					<div class="row mb-3">
						<div class="col-xxl-3 col-xl-4 col-lg-5 col-md-6 col-sm-12">
							<input type="password" name="key" required placeholder="Password" class="form-control"/>
						</div>
					</div>
					<div class="row mb-3">
						<div class="col-xxl-3 col-xl-4 col-lg-5 col-md-6 col-sm-12">
							<input type="submit" value="Sign In" class="btn btn-success form-control">
						</div>
					</div>
				</div>
			</form>
		</section>
	</div>
	</body>
	<?php
require_once __DIR__ . '/Common/htmlFooter.phtml';
